### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by BlackFrog1** [possibly-wrong/skittles#1]
It would be nice to add the dataset here.

**Comment by possibly-wrong** [comment]
I'm not sure what you mean by "add the dataset"? Add it where? Or is there some additional data missing from the existing repo that I might have?

**Comment by frommMoritz** [comment]
If you mean to have the numbers in one single machine readable file there is the [skittles.txt](https://github.com/possibly-wrong/skittles/blob/master/skittles.txt)
